apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-service
  labels:
    app: fastapi-app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app-service
  template:
    metadata:
      labels:
        app: fastapi-app-service
    spec:
      containers:
        - name: fastapi-app-service
          image: pearllakhs/fast_api:b917d2f0d734413a3b9ed4feefd41ff7081874b3
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

 